logging.level.ru.jafti.braintalk.message.processor.impl.MessageProcessorImpl=TRACE
logging.level.ru.jafti.braintalk.message.storage.impl.MessageStorageImpl=TRACE

snowflake.datacenterId=1
snowflake.workerId=2