server.port=9080

logging.level.ru.jafti.braintalk.message.processor.impl.MessageProcessorImpl=TRACE
logging.level.ru.jafti.braintalk.message.storage.impl.MessageStorageImpl=TRACE

snowflake.datacenterId=1
snowflake.workerId=2

# ????????? ??????????? ? ??
spring.datasource.url=${JDBC_URL}
spring.datasource.username=${BT_POSTGRES_USER}
spring.datasource.password=${BT_POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? ???????? ????
spring.sql.init.mode=never

# (???????????) ??????? ??????????? SQL
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
logging.level.ru.jafti.braintalk.online.registry.impl=DEBUG
logging.level.ru.jafti.braintalk.server.connection=DEBUG

# Hikari Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=1200000
spring.datasource.hikari.max-lifetime=1800000