server.port=9080

# Application log settings
logging.level.ru.jafti.braintalk.message.processor.impl.MessageProcessorImpl=TRACE
logging.level.ru.jafti.braintalk.message.storage.impl.MessageStorageImpl=TRACE
logging.level.ru.jafti.braintalk.online.registry.impl=DEBUG
logging.level.ru.jafti.braintalk.server.connection=DEBUG

snowflake.datacenterId=1
snowflake.workerId=2

# Database connection settings
spring.datasource.url=${JDBC_URL}
spring.datasource.username=${BT_POSTGRES_USER}
spring.datasource.password=${BT_POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximumPoolSize=20
spring.sql.init.mode=never

# Debug logging for DB and SQL
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
logging.level.com.zaxxer.hikari=DEBUG