name: Build and publish

on:
  push:
    branches: [ "feature/add-docker-2-maven" ]

jobs:
  build-and-publish:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Build and publish docker
        run: ./mvnw clean package -Dmaven.test.skip=true docker:build docker:push -pl server